<?php
$number1 = 42;
$number2 = 33;
?>




<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Exercice 2 echo</title>
    <style>
        .red {
            color: red;
        }

        .blue {
            color: blue;
        }
    </style>
</head>
<body>
    <?php
    if ($number1 % 2 == 0) {
        echo "<p class='red'>$number1</p>";
    } else {
        echo "<p class='blue'>$number1</p>";
    }

    if ($number2 % 2 == 0) {
        echo "<p class='red'>$number2</p>";
    } else {
        echo "<p class='blue'>$number2</p>";
    }
    ?>
</body>
</html>